obj-$(CONFIG_STM_LSM303D)		+= lsm303d.o
obj-$(CONFIG_STM_L3GD20)		+= l3gd20_gyr.o
#obj-$(CONFIG_STM_L3GD20) 		+= l3gd20_gyr_i2c.o
obj-$(CONFIG_STMVL6180)			+= stmvl6180.o
obj-$(CONFIG_SENSOR_HUB)		+= sensor_hub.o
obj-$(CONFIG_SENSOR_HUB)	   	+= sensor_mux.o
obj-$(CONFIG_SENSOR_EXTENDED)   	+= sensor_extended.o
